insert into PATIENT (PATIENTID, USERNAME, PASSWORD, NAME, WEIGHT, HEIGHT, AGE) values (PATIENT_SEQ.NEXTVAL, 'pedro01', 'password', 'Peter', '75kg', '170cm', 38);
insert into MEDICATION (MEDICATIONID, NAME, DOSAGE, CONDITION, TIMESAWEEK, TIMESADAY, TIMETOTAKE, QUANTITY, PILLSLEFT, REFILL) values (MEDICATION_SEQ.NEXTVAL, 'Paracetamol', '250mg', 'Sore Head', 1, 4, parsedatetime('17 Mar 2012 09:00', 'dd MMM yyyy hh:mm'), 2, 6, 0); 
insert into MEDICATION (MEDICATIONID, NAME, DOSAGE, CONDITION, TIMESAWEEK, TIMESADAY, TIMETOTAKE, QUANTITY, PILLSLEFT, REFILL) values (MEDICATION_SEQ.NEXTVAL, 'Amlodipine', '10mg', 'High Blood Pressure', 7, 1, parsedatetime('17 Mar 2012 09:00', 'dd MMM yyyy hh:mm'), 1, 30, 0);
insert into MEDICATION (MEDICATIONID, NAME, DOSAGE, CONDITION, TIMESAWEEK, TIMESADAY, TIMETOTAKE, QUANTITY, PILLSLEFT, REFILL) values (MEDICATION_SEQ.NEXTVAL, 'Candesartan', '8mg', 'High Blood Pressure', 7, 1, parsedatetime('17 Mar 2012 09:00', 'dd MMM yyyy hh:mm'), 1, 30, 0);
insert into PATIENT_MEDICATION (PATIENT_PATIENTID, MEDICATION_MEDICATIONID) values (1, 1)
insert into PATIENT_MEDICATION (PATIENT_PATIENTID, MEDICATION_MEDICATIONID) values (1, 2)
insert into PATIENT_MEDICATION (PATIENT_PATIENTID, MEDICATION_MEDICATIONID) values (1, 3)

insert into PATIENT (PATIENTID, USERNAME, PASSWORD, NAME, WEIGHT, HEIGHT, AGE) values (PATIENT_SEQ.NEXTVAL, 'robbo02', 'password1', 'Joe', '80kg', '180cm', 40);
insert into MEDICATION (MEDICATIONID, NAME, DOSAGE, CONDITION, TIMESAWEEK, TIMESADAY, TIMETOTAKE, QUANTITY, PILLSLEFT, REFILL) values (MEDICATION_SEQ.NEXTVAL, 'Cholecalciferol', '800units', 'Calcium D Deficiency', 7, 1, parsedatetime('17 Mar 2012 09:00', 'dd MMM yyyy hh:mm'), 2, 30, 0);
insert into MEDICATION (MEDICATIONID, NAME, DOSAGE, CONDITION, TIMESAWEEK, TIMESADAY, TIMETOTAKE, QUANTITY, PILLSLEFT, REFILL) values (MEDICATION_SEQ.NEXTVAL, 'Mirtazapine', '30mg', 'Depression', 7, 1, parsedatetime('17 Mar 2012 09:00', 'dd MMM yyyy hh:mm'), 2, 30, 0);
insert into MEDICATION (MEDICATIONID, NAME, DOSAGE, CONDITION, TIMESAWEEK, TIMESADAY, TIMETOTAKE, QUANTITY, PILLSLEFT, REFILL) values (MEDICATION_SEQ.NEXTVAL, 'Trientine', '300mg', 'Wilsons Disease', 7, 2, parsedatetime('17 Mar 2012 09:00', 'dd MMM yyyy hh:mm'), 4, 100, 0);
insert into PATIENT_MEDICATION (PATIENT_PATIENTID, MEDICATION_MEDICATIONID) values (2, 4)
insert into PATIENT_MEDICATION (PATIENT_PATIENTID, MEDICATION_MEDICATIONID) values (2, 5)
insert into PATIENT_MEDICATION (PATIENT_PATIENTID, MEDICATION_MEDICATIONID) values (2, 6)


